### ISSUE TITLE
New thumbnail for individual project

### ISSUE THREAD

**Issue by jack-hermanson** [jack-hermanson/cis200#142]
Slide 14. What new thumbnail should be used?

**Comment by jack-hermanson** [comment]
Wait for Dr. Serrano to upload image to this issue's comments section.

**Comment by christina-serrano** [comment]
![ecosurf_thumbnail](https://user-images.githubusercontent.com/94719743/148300897-26217b7b-dfd5-4cd7-8341-a1b5a47ed649.PNG)
