### ISSUE TITLE
Ecosurf Company Pitch page

### ISSUE THREAD

**Issue by jack-hermanson** [jack-hermanson/cis200#149]
Lots of good content to add here from slide 20. Can we get that logo image file?

<img width="1319" alt="Screen Shot 2022-01-04 at 5 02 44 PM" src="https://user-images.githubusercontent.com/51171534/148140156-9e996897-74fe-4d69-98ec-320035d71727.png">

**Comment by jack-hermanson** [comment]
Float left image

**Comment by christina-serrano** [comment]
![ecosurf_logo](https://user-images.githubusercontent.com/94719743/148300952-d7db618a-a1ea-4bd4-bbe0-0a37d5584f28.PNG)

adding ecosurf logo
